name: Build VistA API
on:
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Prepare env
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build vista-api war
        env:
          BD_USER: ${{ secrets.BUILD_USER }}
          BD_ACCESS_TOKEN: ${{ secrets.BUILD_ACCESS_TOKEN }}
        run: |
          cp build/mvn/settings.xml ~/.m2/settings.xml
          java -version
          which java
          JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.10-7/x64 mvn clean install
          JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17.0.10-7/x64 mvn clean package
